// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

type ClientJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientJoin) Reset() {
	*x = ClientJoin{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientJoin) ProtoMessage() {}

func (x *ClientJoin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientJoin.ProtoReflect.Descriptor instead.
func (*ClientJoin) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *ClientJoin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ClientLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leave         string                 `protobuf:"bytes,1,opt,name=leave,proto3" json:"leave,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientLeave) Reset() {
	*x = ClientLeave{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientLeave) ProtoMessage() {}

func (x *ClientLeave) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientLeave.ProtoReflect.Descriptor instead.
func (*ClientLeave) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

func (x *ClientLeave) GetLeave() string {
	if x != nil {
		return x.Leave
	}
	return ""
}

type ClientMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ClientId    string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	LogicalTime int64                  `protobuf:"varint,2,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Join
	//	*ClientMessage_Leave
	//	*ClientMessage_Message
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{4}
}

func (x *ClientMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientMessage) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetJoin() *ClientJoin {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *ClientMessage) GetLeave() *ClientLeave {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Leave); ok {
			return x.Leave
		}
	}
	return nil
}

func (x *ClientMessage) GetMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Message); ok {
			return x.Message
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Join struct {
	Join *ClientJoin `protobuf:"bytes,3,opt,name=join,proto3,oneof"`
}

type ClientMessage_Leave struct {
	Leave *ClientLeave `protobuf:"bytes,4,opt,name=leave,proto3,oneof"`
}

type ClientMessage_Message struct {
	Message *ChatMessage `protobuf:"bytes,5,opt,name=Message,proto3,oneof"`
}

func (*ClientMessage_Join) isClientMessage_Payload() {}

func (*ClientMessage_Leave) isClientMessage_Payload() {}

func (*ClientMessage_Message) isClientMessage_Payload() {}

type ServerEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventType      string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	LogicalTime    int64                  `protobuf:"varint,3,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	FromClientId   string                 `protobuf:"bytes,4,opt,name=from_client_id,json=fromClientId,proto3" json:"from_client_id,omitempty"`
	FromClientName string                 `protobuf:"bytes,5,opt,name=from_client_name,json=fromClientName,proto3" json:"from_client_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{5}
}

func (x *ServerEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ServerEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ServerEvent) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

func (x *ServerEvent) GetFromClientId() string {
	if x != nil {
		return x.FromClientId
	}
	return ""
}

func (x *ServerEvent) GetFromClientName() string {
	if x != nil {
		return x.FromClientName
	}
	return ""
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\x12\bchitchat\"\a\n" +
	"\x05Empty\" \n" +
	"\n" +
	"ClientJoin\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"!\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"#\n" +
	"\vClientLeave\x12\x14\n" +
	"\x05leave\x18\x01 \x01(\tR\x05leave\"\xe8\x01\n" +
	"\rClientMessage\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12!\n" +
	"\flogical_time\x18\x02 \x01(\x03R\vlogicalTime\x12*\n" +
	"\x04join\x18\x03 \x01(\v2\x14.chitchat.ClientJoinH\x00R\x04join\x12-\n" +
	"\x05leave\x18\x04 \x01(\v2\x15.chitchat.ClientLeaveH\x00R\x05leave\x121\n" +
	"\aMessage\x18\x05 \x01(\v2\x15.chitchat.ChatMessageH\x00R\aMessageB\t\n" +
	"\apayload\"\xb9\x01\n" +
	"\vServerEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12!\n" +
	"\flogical_time\x18\x03 \x01(\x03R\vlogicalTime\x12$\n" +
	"\x0efrom_client_id\x18\x04 \x01(\tR\ffromClientId\x12(\n" +
	"\x10from_client_name\x18\x05 \x01(\tR\x0efromClientName2F\n" +
	"\bChitChat\x12:\n" +
	"\x04Chat\x12\x17.chitchat.ClientMessage\x1a\x15.chitchat.ServerEvent(\x010\x01B\x16Z\x14ITUServer/grpc/protob\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_proto_goTypes = []any{
	(*Empty)(nil),         // 0: chitchat.Empty
	(*ClientJoin)(nil),    // 1: chitchat.ClientJoin
	(*ChatMessage)(nil),   // 2: chitchat.ChatMessage
	(*ClientLeave)(nil),   // 3: chitchat.ClientLeave
	(*ClientMessage)(nil), // 4: chitchat.ClientMessage
	(*ServerEvent)(nil),   // 5: chitchat.ServerEvent
}
var file_proto_proto_depIdxs = []int32{
	1, // 0: chitchat.ClientMessage.join:type_name -> chitchat.ClientJoin
	3, // 1: chitchat.ClientMessage.leave:type_name -> chitchat.ClientLeave
	2, // 2: chitchat.ClientMessage.Message:type_name -> chitchat.ChatMessage
	4, // 3: chitchat.ChitChat.Chat:input_type -> chitchat.ClientMessage
	5, // 4: chitchat.ChitChat.Chat:output_type -> chitchat.ServerEvent
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	file_proto_proto_msgTypes[4].OneofWrappers = []any{
		(*ClientMessage_Join)(nil),
		(*ClientMessage_Leave)(nil),
		(*ClientMessage_Message)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
